---
name: Test_Experiment_Script
tenant_id: tenantid
force_login: false
workspace:
  subscription_id: subscription_id
  resource_group: resource_group
  workspace_name: workspace_name
compute_name: cluster
environment:
  name: experiment_env
  dependencies:
  - python=3.7
  - pip:
    - azureml-defaults
scripts:
  folder: experiment_scripts
  main: main.py
data:
  input:
    - name: input_data
      data_store_name: input_datastore
      container_name: container
      mount_path: input
      parameter_name: input_path
      readonly: true
      register: true
      account_name: account
      account_key: xxx
  output:
    - name: output_data
      data_store_name: output_datastore
      container_name: container
      mount_path: output
      parameter_name: output_path
      register: true
      account_name: account
      account_key: xxx
parameters:
  input_file: test.txt
  output_file: test.txt
