---
name: Copy_Data_Script
tenant_id: tenantid
force_login: false
workspace:
  subscription_id: subscription_id
  resource_group: resource_group
  workspace_name: workspace_name
compute_name: cluster
environment:
  name: experiment_env
  dependencies:
  - python=3.7
  - pip:
    - azureml-defaults
scripts:
  folder: copy_data_scripts
  main: main.py
data:
  input:
    - name: input_data
      mount_path: input
      parameter_name: input_path
      readonly: true
      datastore:
        name: input_datastore
        register: true
        container_name: container
        account_name: account
        account_key: xxx
  output:
    - name: output_data
      mount_path: output
      parameter_name: output_path
      datastore:
        name: output_datastore
        register: true
        container_name: container
        account_name: account
        account_key: xxx
parameters:
  input_file: test.txt
  output_file: test.txt
