---
name: Copy_Data_Job
provider: 
  azureml:
    workspace:
      subscription_id: subscription_id
      resource_group: resource_group
      workspace_name: workspace_name
    compute_name: cluster
job:
  code:
    folder: copy_data_scripts
    main: main.py
  inputs:
  - input_data
  outputs:
  - output_data
  parameters:
    input_file: test.txt
    output_file: test1.txt
  environment:
    name: experiment_env
    dependencies:
    - python=3.7
    - pip:
      - azureml-defaults
data:
  input_data:
    type: dataset
    parameter_name: input_path
    mount_path: input
    datastore:
      name: input_datastore
  output_data:
    type: datareference
    parameter_name: output_path
    mount_path: output
    datastore:
      name: output_datastore
