---
name: Copy_Data_Script
provider: 
  azureml:
    tenant_id: tenantid
    force_login: false
    workspace:
      subscription_id: subscription_id
      resource_group: resource_group
      workspace_name: workspace_name
    compute_name: cluster
environment:
  name: experiment_env
  dependencies:
  - python=3.7
  - pip:
    - azureml-defaults
scripts:
  folder: copy_data_scripts
  main: main.py
data:
  input:
  - dataset:
      name: input_data
      parameter_name: input_path
      mount_path: input
      datastore:
        name: input_datastore
  output:
  - datareference:
      name: output_data
      parameter_name: output_path
      mount_path: output
      datastore:
        name: output_datastore
parameters:
  input_file: test.txt
  output_file: test.txt
